version: '3.8'

services:
  web:
    build:
      context: ./QAPPBuilder
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./QAPPBuilder:/app
      - static_volume:/app/qapp_builder/static
      - media_volume:/app/qapp_builder/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/qappbuilder
      - DJANGO_SETTINGS_MODULE=qapp_builder.settings
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=qappbuilder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume: