# Generated by Django 2.2.4 on 2019-08-02 18:18
# pylint: skip-file

import os
from django.core import serializers
from django.db import migrations, transaction
from django.db.utils import IntegrityError

fixture_dir = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'disciplines.json'


def load_fixture(_apps, _schema_editor):
    """Load data from a fixture when running migrations"""
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        try:
            with transaction.atomic():
                obj.save()
        except IntegrityError:
            pass    # Ignore if duplicate obj already exists in db
    fixture.close()


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
        # Set the auto increment value to start after the imported fixture ids
        migrations.RunSQL(
            "SELECT setval('qapp_builder_discipline_id_seq', max(id)) FROM qapp_builder_discipline;",
            migrations.RunSQL.noop),
    ]
