# Generated by Django 5.1.5 on 2025-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0002_alter_sectiona1_definitions_alter_sectiona1_versions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiona1',
            name='definitions',
            field=models.ManyToManyField(blank=True, to='qapp_builder.definition'),
        ),
        migrations.AlterField(
            model_name='sectiona1',
            name='versions',
            field=models.ManyToManyField(blank=True, to='qapp_builder.versioncontrol'),
        ),
        migrations.AlterField(
            model_name='sectiona12',
            name='docs_records',
            field=models.ManyToManyField(blank=True, to='qapp_builder.qappdocument'),
        ),
        migrations.AlterField(
            model_name='sectiona7',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, to='qapp_builder.participant'),
        ),
    ]
