# Generated by Django 5.1.6 on 2025-04-15 17:21

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0002_load_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiona10',
            name='org_chart',
            field=models.FileField(blank=True, help_text='Upload the organizational chart', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='/srv/app/qapp_builder/media/uploads'), upload_to=constants.utils.get_qapp_attachment_storage_path),
        ),
    ]
