# Generated by Django 5.1.5 on 2025-02-24 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0002_load_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiona2',
            name='additional_signatures',
        ),
        migrations.AddField(
            model_name='additionalsignature',
            name='section_a2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectiona2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectiona1',
            name='intra_or_extra',
            field=models.CharField(choices=[('Intramurally', 'Intramurally'), ('Extramurally', 'Extramurally')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sectiona1',
            name='qa_category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1),
        ),
    ]
