# Generated by Django 5.1.5 on 2025-02-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0003_alter_sectiona1_definitions_alter_sectiona1_versions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiona1',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='versioncontrol',
            name='qapp_id',
        ),
        migrations.AddField(
            model_name='versioncontrol',
            name='section_a1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectiona1'),
            preserve_default=False,
        ),
    ]
