# Generated by Django 5.1.5 on 2025-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0003_remove_sectiona2_additional_signatures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalsignature',
            name='is_epa',
            field=models.BooleanField(default=True),
        ),
    ]
