# Generated by Django 5.1.5 on 2025-02-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0004_additionalsignature_is_epa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalsignature',
            name='is_epa',
        ),
    ]
