# Generated by Django 5.1.6 on 2025-04-09 19:31

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0004_alter_sectionb7_qapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsectiona10',
            name='org_chart',
            field=models.TextField(blank=True, help_text='Upload the organizational chart', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectiona10',
            name='org_chart',
            field=models.FileField(blank=True, help_text='Upload the organizational chart', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='C:\\git\\projects\\epa\\jacob_qappbuilder\\QAPPBuilder\\qapp_builder/media\\uploads'), upload_to=constants.utils.get_qapp_attachment_storage_path),
        ),
    ]
