# Generated by Django 5.1.5 on 2025-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0004_remove_sectiona1_versions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontrol',
            name='qapp_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
