# Generated by Django 5.1.6 on 2025-04-10 13:08

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0005_alter_historicalsectiona10_org_chart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiona10',
            name='org_chart',
            field=models.FileField(blank=True, help_text='Upload the organizational chart', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\git\\projects\\epa\\jacob_qappbuilder\\QAPPBuilder\\qapp_builder/media\\uploads'), upload_to=constants.utils.get_qapp_attachment_storage_path),
        ),
    ]
