# Generated by Django 5.1.5 on 2025-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0005_versioncontrol_qapp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiona2',
            name='epa_op_man',
            field=models.TextField(verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='versioncontrol',
            name='updated_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
