# Generated by Django 5.1.5 on 2025-02-24 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0005_remove_additionalsignature_is_epa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acronymabbreviation',
            name='section_a3',
        ),
        migrations.AddField(
            model_name='acronymabbreviation',
            name='qapp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.qapp'),
            preserve_default=False,
        ),
    ]
