# Generated by Django 5.1.5 on 2025-02-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0006_remove_acronymabbreviation_section_a3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='qapp_id',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='section_a3',
        ),
        migrations.AddField(
            model_name='revision',
            name='qapp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.qapp'),
            preserve_default=False,
        ),
    ]
