# Generated by Django 5.1.5 on 2025-02-18 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0006_alter_sectiona2_epa_op_man_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionBStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_field', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qapp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_b', to='qapp_builder.qapp')),
                ('standard_inputs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionbstandard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelApplicationEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExistingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeBasedModeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionBDisciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.TextField(choices=[('Measurement and Monitoring', 'Measurement and Monitoring'), ('Environmental Technology', 'Environmental Technology'), ('Existing Data', 'Existing Data'), ('Model Application and Evaluation', 'Model Application and Evaluation'), ('Code-Based Modeling', 'Code-Based Modeling'), ('Software and Application Development', 'Software and Application Development'), ('Social Sciences', 'Social Sciences')])),
                ('section_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialSciences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareApplicationDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
