# Generated by Django 5.1.5 on 2025-02-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0007_remove_revision_qapp_id_remove_revision_section_a3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='name_and_org',
            new_name='name',
        ),
        migrations.AddField(
            model_name='distribution',
            name='org',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
