# Generated by Django 5.1.6 on 2025-04-10 13:34

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0007_alter_sectiona10_org_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiona10',
            name='org_chart',
            field=models.FileField(blank=True, help_text='Upload the organizational chart', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='C:\\git\\projects\\epa\\jacob_qappbuilder\\QAPPBuilder\\qapp_builder/media\\uploads'), upload_to=constants.utils.get_qapp_attachment_storage_path),
        ),
    ]
