# Generated by Django 5.1.5 on 2025-02-05 16:41

import constants.utils
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0008_sectionb_types_rework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/home/gqc/git/projects/epa/qappbuilder/QAPPBuilder/qapp_builder/media/uploads'), upload_to=constants.utils.get_attachment_storage_path),
        ),
        migrations.AlterField(
            model_name='sectionbtypemap',
            name='sectionb_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qapp_builder.sectionbtype'),
        ),
    ]
