# Generated by Django 5.1.5 on 2025-02-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0008_rename_name_and_org_distribution_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='section_a7',
        ),
        migrations.AddField(
            model_name='distribution',
            name='qapp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.qapp'),
            preserve_default=False,
        ),
    ]
