# Generated by Django 5.1.5 on 2025-02-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0009_remove_distribution_section_a7_distribution_qapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleresponsibility',
            old_name='name_and_org',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='roleresponsibility',
            name='section_a8',
        ),
        migrations.AddField(
            model_name='roleresponsibility',
            name='org',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleresponsibility',
            name='qapp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.qapp'),
            preserve_default=False,
        ),
    ]
