# Generated by Django 5.1.5 on 2025-02-25 18:13

import constants.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0010_rename_name_and_org_roleresponsibility_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionA10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_chart', models.FileField(blank=True, null=True, upload_to=constants.utils.get_attachment_storage_path)),
                ('qapp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_a10', to='qapp_builder.qapp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
