# Generated by Django 5.1.5 on 2025-02-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0012_remove_documentrecord_section_a12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionb',
            name='b7_1',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='b7_2',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='b7_3',
        ),
        migrations.AddField(
            model_name='hardwaresoftware',
            name='qapp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.qapp'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SectionB7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b7_1', models.TextField()),
                ('b7_2', models.TextField()),
                ('section_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.sectionb')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
