# Generated by Django 5.1.5 on 2025-02-25 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0013_remove_sectionb_b7_1_remove_sectionb_b7_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionb7',
            name='section_b',
        ),
        migrations.AddField(
            model_name='sectionb7',
            name='qapp',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='qapp_builder.qapp'),
            preserve_default=False,
        ),
    ]
