# Generated by Django 5.1.5 on 2025-02-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0014_remove_sectionb7_section_b_sectionb7_qapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionb7',
            old_name='b7_1',
            new_name='b71',
        ),
        migrations.RenameField(
            model_name='sectionb7',
            old_name='b7_2',
            new_name='b72',
        ),
    ]
