# Generated by Django 5.1.6 on 2025-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0015_rename_b7_1_sectionb7_b71_rename_b7_2_sectionb7_b72'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiona1',
            name='title',
        ),
    ]
