DISCIPLINE_MM_STR = 'Measurement and Monitoring'
DISCIPLINE_SS_STR = 'Social Sciences'
DISCIPLINE_ED_STR = 'Existing Data'
DISCIPLINE_CBM_STR = 'Code-Based Modeling'
DISCIPLINE_MAE_STR = 'Model Application and Evaluation'
DISCIPLINE_SAD_STR = 'Software and Application Development'
DISCIPLINE_ET_STR = 'Environmental Technology'

DISCIPLINE_CHOICES = (
    (DISCIPLINE_MM_STR, DISCIPLINE_MM_STR),
    (DISCIPLINE_SS_STR, DISCIPLINE_SS_STR),
    (DISCIPLINE_ED_STR, DISCIPLINE_ED_STR),
    (DISCIPLINE_CBM_STR, DISCIPLINE_CBM_STR),
    (DISCIPLINE_MAE_STR, DISCIPLINE_MAE_STR),
    (DISCIPLINE_SAD_STR, DISCIPLINE_SAD_STR),
    (DISCIPLINE_ET_STR, DISCIPLINE_ET_STR),
)

# Programmatic solution to get max len?
DISCIPLINE_MAX_LEN = max(len(choice[0]) for choice in DISCIPLINE_CHOICES)

QA_CATEGORY_A = 'A'
QA_CATEGORY_B = 'B'
QA_CATEGORY_OPTIONS = (
    (QA_CATEGORY_A, QA_CATEGORY_A),
    (QA_CATEGORY_B, QA_CATEGORY_B),
)

INTRAMURALLY = 'Intramurally'
EXTRAMURALLY = 'Extramurally'
INTRA_EXTRA_CHOICES = (
    (INTRAMURALLY, INTRAMURALLY),
    (EXTRAMURALLY, EXTRAMURALLY),
)

CURRENT_FY = 2025
QUARTERS = ['Q1', 'Q2', 'Q3', 'Q4']

FY_QUARTERS = [
    f'FY{CURRENT_FY-1} {QUARTERS[3]}',  # FY24 Q4
    f'FY{CURRENT_FY} {QUARTERS[0]}',    # FY25 Q1
    f'FY{CURRENT_FY} {QUARTERS[1]}',    # FY25 Q2
    f'FY{CURRENT_FY} {QUARTERS[2]}',    # FY25 Q3
    f'FY{CURRENT_FY} {QUARTERS[3]}',    # FY25 Q4
    f'FY{CURRENT_FY+1} {QUARTERS[0]}',  # FY26 Q1
    f'FY{CURRENT_FY+1} {QUARTERS[1]}',  # FY26 Q2
    f'FY{CURRENT_FY+1} {QUARTERS[2]}',  # FY26 Q3
]
