DISCIPLINE_MM_STR = 'Measurement and Monitoring'
DISCIPLINE_ET_STR = 'Environmental Technology'
DISCIPLINE_ED_STR = 'Existing Data'
DISCIPLINE_MAE_STR = 'Model Application and Evaluation'
DISCIPLINE_CBM_STR = 'Code-Based Modeling'
DISCIPLINE_SAD_STR = 'Software and Application Development'
DISCIPLINE_SS_STR = 'Social Sciences'

DISCIPLINE_CHOICES = (
  (DISCIPLINE_MM_STR, DISCIPLINE_MM_STR),
  (DISCIPLINE_ET_STR, DISCIPLINE_ET_STR),
  (DISCIPLINE_ED_STR, DISCIPLINE_ED_STR),
  (DISCIPLINE_MAE_STR, DISCIPLINE_MAE_STR),
  (DISCIPLINE_CBM_STR, DISCIPLINE_CBM_STR),
  (DISCIPLINE_SAD_STR, DISCIPLINE_SAD_STR),
  (DISCIPLINE_SS_STR, DISCIPLINE_SS_STR)
)
